posts/serializers.py, posts/urls.py, posts/views.py
=> 게시글 수정, 삭제 기능 구현 완료

posts/urls.py, posts/views.py
=> 댓글 수정, 삭제 기능 구현 완료

accounts/templates/accounts/profile.html, accounts/templates/accounts/profile_update.html
=> access token 인증 방식 변경

playlist/templates/playlist/playlist.html, playlist/urls.py, playlist/views.py, static/css/playlist.css, static/js/playlist.js
2024.05.24
1. playlist html 별도의 경로로 들어와야 하는걸 기본 url로 변경
2. 검색 버튼 제거 후 엔터 누르면 playlist 검색 기능으로 작동되게 변
3. playlist 듣기 버튼 제거 후 이미지 또는 타이틀 눌렀을 때 해당 페이지로 이동되게 변경
=> playlist 경로 설정, playlist 편의성 추가

accounts/static/accounts/css/login.css, accounts/static/accounts/css/signup.css, accounts/templates/accounts/login.html, accounts/templates/accounts/signup.html, templates/base.html
240525
1. css에 알아보기 쉽게 주석 달아 놓았으니 참고
2. containor공간 만들어주기 위해 base.html 수정
=> 로그인, 회원가입 html,css 완료

static/js/base.js
=> 테스트용 로직 제거

posts/static/posts/css/list.css, posts/templates/posts/list.html, posts/urls.py
=> 게시글 list html, css 완

accounts/static/accounts/css/login.css, accounts/templates/accounts/signup.html, posts/static/posts/css/create.css, posts/static/posts/css/detail.css, posts/static/posts/css/list.css, posts/templates/posts/create.html, posts/urls.py
240527
1. 다른 css input값 글자 색이랑 폰트 다 수정
2. signup css, html test->signup 글자 수정
=> post create html css 완료

posts/static/posts/css/update.css, posts/templates/posts/update.html, posts/urls.py
240528
1. 작성페이지랑 크게 다르지 않음.
2. 기존 데이터 불러오는 건 js에서 처리해야 함
=> post update html,css 완료

posts/templates/posts/detail.html, static/js/base.js
2024.05.30
refresh token 만료 안되면 blacklist에 추가, 만료 되있으면 그냥 삭제
=> refresh token이 만료된 상태에서 Logout 가능하게 하는 로직

WhateverSong/settings.py, playlist/views.py
2024.05.31
1. settings.py redis 주소 루트 변경
2. cache 30분으로 시간 변경
=> redis 주소 루트 변경, cache 시간 조절

accounts/static/accounts/js/signup.js, coach/static/coach/js/coach.js, posts/static/posts/js/create.js, posts/static/posts/js/detail.js, posts/templates/posts/detail.html, posts/views.py
2024.06.03
html에서 form 내에 선택한 파일 이름이 보이도록 변경
=> posts/create, accounts/signup, coach/coach 이미지 파일, mp4 파일 선택했을 때, 파일 이름 보여주도록 변경

accounts/static/accounts/js/profile.js, accounts/static/accounts/js/profile_update.js, accounts/static/accounts/js/signup.js, coach/static/coach/js/coach.js, coach/static/coach/js/coach_result.js, playlist/static/playlist/js/playlist.js, posts/static/posts/js/update.js
2024.06.03
access token 불러오는 변수명 전체 js에서 조정, 모든 console.log 삭제
=> 전체 js 변수명 조정

accounts/static/accounts/css/profile.css, accounts/static/accounts/js/profile.js, accounts/templates/accounts/profile.html, posts/static/posts/css/list.css, posts/static/posts/js/list.js
240604
1. profile css 디테일 수정 필요
2. '내가 받은 훈수' 부분은 아직 안 함
=> post list css, profile css 완료

Readme.md, playlist/static/playlist/js/playlist.js, playlist/views.py
2024.06.04
1. playlist/views.py 불필요한 주석 변경
2. playlist.js 찜하기 안넘어가는거 변경
3. readme erd 추가
=> readme erd 추가, views.py 주석 변경 및 playlist.js 코드 변경 

accounts/serializers.py
=> accounts/serializers.py 수정

posts/static/posts/js/list.js
2024.06.05
posts/list.js 로직 수정
=> posts/list.js list에서 content 내용이 50자가 넘어 갈 시 ...으로 나머지 내용을 대체하도록 변경

accounts/static/accounts/css/signup.css, accounts/templates/accounts/signup.html
2024.06.05
1. profile image 파일 이름에 따라 바뀌는 칸 css 수정
=> profile image css 수정

accounts/static/accounts/css/profile.css, posts/static/posts/css/create.css, posts/static/posts/css/detail.css, posts/static/posts/css/update.css, posts/static/posts/js/detail.js, posts/templates/posts/detail.html
240605
1. 게시글 작성시 내용칸이 좁아 보여서 넓게 수정하고, 그거에 맞춰서 다른 input칸도 수정
2. profile 페이지에서 보이는 닉네임 다른 글씨랑 폰트 같게 수정
=> post update, create, profile nickname 부분 css 보충 완료

accounts/static/accounts/css/profile.css, accounts/static/accounts/js/profile.js, coach/static/coach/css/coach_result.css, coach/templates/coach/coach_result.html
=> coach result, profile-내가 받은 훈수 부분 css 보충

accounts/static/accounts/js/profile_update.js, playlist/static/playlist/js/playlist.js
2024.06.07
accounts/profile_update.js submit 로직 추가
playlists.js searchPlaylist 함수에 checkUserZzimPlaylists 함수 호출 로직 추가
=> profile 수정에서 nickname 수정 시, localStorage nickname 삭제, 새 nickname 추가, playlist 검색 시 zzim버튼 활성화 오류 해결 

posts/models.py, posts/static/posts/js/update.js, posts/templates/posts/update.html
2024.06.07
posts/models.py , accounts/models.py 수정 -> migrate 불필요
=> post 수정 시 노래 링크 안넣어도 수정되게끔 변경, Default image 이름 변경

playlist/static/playlist/js/playlist.js, playlist/urls.py, posts/static/posts/js/create.js, posts/static/posts/js/list.js, posts/urls.py, static/js/base.js, templates/base.html
=> interceptor 로직 수정, playlist url 수정, post url 수정 

accounts/static/accounts/js/profile_update.js
2024.06.08
profile_update.js 수정
=> 비밀번호 변경 시 이동 페이지 url 수정
